#! /bin/sh -

create_endpoint="/channels/{channel.id}/messages"
read_endpoint="/channels/{channel.id}/message/{message.id}"
update_endpoint="/channels/{channel.id}/message/{message.id}"
delete_endpoint="/channels/{channel.id}/message/{message.id}"

# `discord channel-message create --channel "..."`
# https://discordapp.com/developers/docs/resources/channel#create-message
channel_message_create() {
    request "POST" "$(replace_tokens "$create_endpoint")"
}

# `discord channel-message read --channel "..." --message "..."`
# https://discordapp.com/developers/docs/resources/channel#get-channel-message
channel_message_read() {
    request "GET" "$(replace_tokens "$read_endpoint")"
}

# `discord channel-message update --channel "..." --message "..."`
# https://discordapp.com/developers/docs/resources/channel#edit-message
channel_message_update() {
    request "PATCH" "$(replace_tokens "$update_endpoint")"
}

# `discord channel-message delete --channel "..." --message "..."`
# https://discordapp.com/developers/docs/resources/channel#delete-message
channel_message_delete() {
    request "DELETE" "$(replace_tokens "$delete_endpoint")"
}
