#! /bin/sh -

read_endpoint="/guilds/{guild.id}/channels"
update_endpoint="/guilds/{guild.id}/channels"

# `discord guild-channels read --guild="..."`
# https://discordapp.com/developers/docs/resources/guild#get-guild-channels
guild_channels_read() {
    log_debug "Reading Guild Channels"

    validate_opts_guild

    request "GET" "$(echo "$read_endpoint" | sed "s/{guild.id}/$OPTS_GUILD/")"
}

# `discord guild-channels update --guild="..."`
# https://discordapp.com/developers/docs/resources/guild#modify-guild-channel-positions
guild_channels_update() {
    method="PATCH"
    log_debug "Updating Guild Channels Position"
}
