#! /bin/sh -

create_endpoint="/guilds/{guild.id}"
read_endpoint="/guilds"
update_endpoint="/guilds/{guild.id}"
delete_endpoint="/guilds/{guild.id}"

# `discord guild create`
# https://discordapp.com/developers/docs/resources/guild#create-guild
guild_create() {
    request "POST" "$(replace_tokens "$create_endpoint")"
}

# `discord guild read --guild="..."`
# https://discordapp.com/developers/docs/resources/guild#get-guild
guild_read() {
    request "GET" "$(replace_tokens "$read_endpoint")"
}

# `discord guild update --guild="..."`
# https://discordapp.com/developers/docs/resources/guild#modify-guild
guild_update() {
    request "PATCH" "$(replace_tokens "$update_endpoint")"
}

# `discord guild delete --guild="..."`
# https://discordapp.com/developers/docs/resources/guild#delete-guild
guild_delete() {
    request "DELETE" "$(replace_tokens "$delete_endpoint")"
}
